import Link from "next/link";
import { rsvpLabels, attendanceLabel, type GuestView } from "@/modules/guests/schemas";
import { eventDayLabel } from "@/modules/events/dates";
import { GuestActions } from "./guest-actions";
import { SharingCard } from "@/components/invitations/sharing-card";
import styles from "@/components/invitations/sharing.module.css";
export function GuestDetails({ guest, timeZone, userId, weddingId, saved }: { guest: GuestView; timeZone: string; userId: string; weddingId: string; saved?: string }) {
  const active = guest.invitedEvents.filter(event => !event.archivedAt);
  return <main id="wedding-content" className={styles.page}><Link href="/guests" className={styles.back}>← Guests / {guest.name} / Invitation &amp; sharing</Link>{saved && <p role="status" className={styles.success}>{saved === "created" ? "Guest created." : "Guest updated."}</p>}<p className={styles.eyebrow}>Invitation &amp; guest access</p><div className={styles.heading}><div><h1>Guest details &amp; invitation link</h1><p>Manage {guest.name}’s personal invitation link, party size, and invited celebrations.</p></div><a href={`/guests/${guest.id}/edit`} className={styles.secondary}>Edit guest</a></div><div className={styles.grid}><div className={styles.left}><SharingCard key={guest.id} guestId={guest.id} name={guest.name} maxGuests={guest.maxGuests}/>{guest.notes && <section className={`${styles.card} ${styles.notes}`}><h2>Wedding team notes</h2><p>{guest.notes}</p></section>}<div className={styles.delete}><GuestActions guest={guest} userId={userId} weddingId={weddingId} details/></div></div><aside className={styles.right}><section className={styles.card}><div className={styles.contactHeading}><span className={styles.avatar} aria-hidden="true">{guest.name.trim().split(/\s+/).slice(0, 2).map(word => word[0]).join("")}</span><div><h2>Contact Registry</h2><p>Guest invitation record</p></div></div><dl className={styles.contact}><div><dt>Primary email</dt><dd>{guest.email || "Not provided"}</dd></div><div><dt>Primary phone</dt><dd>{guest.phone || "Not provided"}</dd></div><div><dt>Overall RSVP status</dt><dd>{rsvpLabels[guest.rsvpStatus]} · {attendanceLabel(guest)}</dd></div><div><dt>Maximum party size</dt><dd>{guest.maxGuests} {guest.maxGuests === 1 ? "person" : "people"}, including the named guest</dd></div></dl></section><section className={styles.card}><h2>Permitted Ceremonies</h2><p>{active.length} active {active.length === 1 ? "event" : "events"}. Only these invited celebrations appear on the guest’s page.</p><ul className={styles.events}>{guest.invitedEventIds.map(id => { const event = guest.invitedEvents.find(event => event.id === id); return <li key={id}>{event ? <><Link href={`/events/${id}`}>{event.name}</Link>{event.archivedAt && <span className={styles.badge}>Archived — hidden from invitation</span>}<small>{eventDayLabel(event.startsAt, timeZone)}</small></> : "Event unavailable — hidden from invitation"}</li>; })}</ul>{!guest.invitedEventIds.length && <p>No events selected yet. You can choose events when editing this guest.</p>}</section><section className={styles.principle}><p className={styles.eyebrow}>A link to your celebration</p><h2>One invitation.<br/>One familiar link.</h2><p>{guest.name} can bookmark this link and return to view their invited events or update their RSVP. Sharing it again keeps the same address.</p></section></aside></div></main>;
}