/* eslint-disable @next/next/no-html-link-for-pages -- Enter forms with document navigation so browser Back triggers the native unsaved-changes guard. */
import Link from "next/link";
import type { WeddingEvent } from "@/modules/events/schemas";
import { eventDateParts, eventDayLabel, eventTimeRange } from "@/modules/events/dates";
import { Icon } from "@/components/home/icon";
import { ArchiveEventButton } from "./archive-button";
import styles from "./events.module.css";
export function EventList({ events, timeZone, includeArchived, userId, weddingId }: { events: WeddingEvent[]; timeZone: string; includeArchived: boolean; userId: string; weddingId: string }) {
  const groups = new Map<string, WeddingEvent[]>();
  for (const event of events) { const day = eventDateParts(event.startsAt, timeZone).date; groups.set(day, [...(groups.get(day) ?? []), event]); }
  return <main id="wedding-content" className={styles.page}>
    <p className={styles.eyebrow}>Planning / Events</p><div className={styles.pageHeading}><div><h1>Wedding events</h1><p>Bring every celebration together in one place.</p></div><a href="/events/new" className={styles.primary}>+ Add event</a></div>
    <div className={styles.toolbar}><span><Icon name="globe" size={14}/>All times in {timeZone}</span><Link href={includeArchived ? "/events" : "/events?includeArchived=true"} role="switch" aria-checked={includeArchived} className={styles.toggle}>Show archived events <span aria-hidden="true" className={includeArchived ? styles.switchOn : styles.switchOff}/></Link></div>
    {events.length === 0 ? <section className={styles.empty}><div className={styles.emptyIcon}><Icon name="calendar" size={38}/></div><h2>{includeArchived ? "No events to show" : "Every celebration starts with a plan."}</h2><p>Add your first event, from Mehendi to the wedding ceremony.</p><a href="/events/new" className={styles.primary}>+ Add your first event</a><small>You can schedule multiple ceremonies, set dress codes, and update details anytime.</small></section> : [...groups].map(([day, rows]) => <section key={day} className={styles.group}><h2><span aria-hidden="true">•</span>{eventDayLabel(rows[0].startsAt, timeZone)}<small>{rows.length} {rows.length === 1 ? "event" : "events"}</small></h2>{rows.map(event => <article key={event.id} className={`${styles.eventCard} ${event.archivedAt ? styles.archived : ""}`}><div className={styles.cardMain}><div className={styles.cardTitle}><span className={styles.type}>{event.type ?? "CUSTOM"}</span><h3><Link href={`/events/${event.id}`}>{event.name}</Link></h3>{event.archivedAt && <span className={styles.archivedBadge}>Archived</span>}</div><div className={styles.meta}><span><Icon name="calendar" size={14}/>{eventTimeRange(event.startsAt, event.endsAt, timeZone)}</span>{event.venueName && <span><Icon name="location" size={14}/>{event.venueName}</span>}</div>{event.dressCode && <p className={styles.small}>Dress code: {event.dressCode}</p>}{event.description && <p className={styles.excerpt}>{event.description}</p>}</div><div className={styles.cardActions}><div>{!event.archivedAt && <a href={`/events/${event.id}/edit`} className={styles.secondary}>Edit</a>}<Link href={`/events/${event.id}`} className={styles.detailsLink}>View details</Link></div><ArchiveEventButton event={event} userId={userId} weddingId={weddingId}/></div></article>)}</section>)}
  </main>;
}