/* eslint-disable @next/next/no-html-link-for-pages -- Document navigation into task forms preserves the native browser Back draft guard. */
import Link from "next/link";
import { statusLabels, priorityLabels, taskStatuses, taskPriorities, type TaskOptions, type TaskListResult, type TaskQuery } from "@/modules/tasks/schemas";
import { taskDateLabel, isTaskOverdue } from "@/modules/tasks/dates";
import { Icon } from "@/components/home/icon";
import { TaskActions } from "./task-actions";
import styles from "./tasks.module.css";
export function TaskList({ result, choices, query, timeZone, today, userId, weddingId, deleted }: { result: TaskListResult; choices: TaskOptions; query: TaskQuery; timeZone: string; today: string; userId: string; weddingId: string; deleted?: boolean }) {
  const completed = query.status === "COMPLETED" && !query.mine;
  const filtered = Boolean(query.priority || query.eventId || query.assignedMembershipId || (query.status && !completed));
  const pageUrl = (page: number) => { const params = new URLSearchParams(); for (const [key, value] of Object.entries(query)) if (value !== undefined && value !== false) params.set(key, String(value)); params.set("page", String(page)); return `/tasks?${params}`; };
  return <main id="wedding-content" className={styles.page}><p className={styles.eyebrow}>Planning / Tasks</p><div className={styles.heading}><div><h1>Wedding tasks</h1><p>Bring your people and plans together, one task at a time.</p></div><a className={styles.primary} href="/tasks/new">+ Add task</a></div>{deleted && <p role="status" className={styles.success}>Task deleted.</p>}
    <nav className={styles.tabs} aria-label="Task views"><Link href="/tasks" aria-current={!query.mine && !completed ? "page" : undefined}>All Tasks</Link><Link href="/tasks?mine=true" aria-current={query.mine ? "page" : undefined}>My Tasks</Link><Link href="/tasks?status=COMPLETED" aria-current={completed ? "page" : undefined}>Completed</Link></nav>
    <form action="/tasks" method="GET" className={styles.filters} key={JSON.stringify(query)}>{query.mine && <input type="hidden" name="mine" value="true"/>}<div className={styles.filterGrid}><label>Status<select name="status" defaultValue={query.status ?? ""}><option value="">All statuses</option>{taskStatuses.map(status => <option key={status} value={status}>{statusLabels[status]}</option>)}</select></label><label>Priority<select name="priority" defaultValue={query.priority ?? ""}><option value="">All priorities</option>{taskPriorities.map(priority => <option key={priority} value={priority}>{priorityLabels[priority]}</option>)}</select></label><label>Event<select name="eventId" defaultValue={query.eventId ?? ""}><option value="">All events</option><option value="none">General wedding task</option>{choices.events.map(event => <option key={event.id} value={event.id}>{event.name}{event.archivedAt ? " (Archived)" : ""}</option>)}</select></label><label>Assigned member<select name="assignedMembershipId" defaultValue={query.assignedMembershipId ?? ""}><option value="">All members</option><option value="none">Unassigned</option>{choices.members.map(member => <option key={member.id} value={member.id}>{member.name}{member.id === choices.currentMembershipId ? " (You)" : ""}</option>)}</select></label></div><div className={styles.filterFooter}><span>{query.mine ? "Showing tasks assigned to you" : completed ? "Showing completed tasks" : "Showing wedding tasks"}</span><button type="submit" className={styles.secondary}>Apply filters</button>{(filtered || completed || query.mine) && <Link href="/tasks">Clear filters</Link>}</div></form>
    {result.data.length ? <><div className={styles.list}>{result.data.map(task => <article key={task.id} className={styles.row}><div className={styles.rowContent}><div className={styles.rowHeading}><h2><Link href={`/tasks/${task.id}`}>{task.title}</Link></h2><span className={`${styles.badge} ${styles[task.priority]}`}>{priorityLabels[task.priority]}{task.priority === "HIGH" ? " priority" : ""}</span>{isTaskOverdue(task, timeZone, today) && <span className={styles.overdue}>Overdue</span>}</div><div className={styles.meta}><span><Icon name="users" size={12}/>{task.assignee?.name ?? (task.assignedMembershipId ? "Former member" : "Unassigned")}</span><span>{task.event?.name ?? (task.eventId ? "Event unavailable" : "General wedding task")}{task.event?.archivedAt && " (Archived)"}</span><span className={isTaskOverdue(task, timeZone, today) ? styles.overdueText : undefined}>{task.dueDate ? `Due: ${taskDateLabel(task.dueDate, timeZone)}` : "No due date"}</span>{task.completedAt && <span>Completed {taskDateLabel(task.completedAt, timeZone)}</span>}</div></div><TaskActions task={task} userId={userId} weddingId={weddingId}/></article>)}</div><div className={styles.pagination}><span>Showing {(query.page - 1) * query.limit + 1}–{(query.page - 1) * query.limit + result.data.length} of {result.pagination.total} tasks</span><div>{query.page > 1 && <Link href={pageUrl(query.page - 1)}>← Previous</Link>}<span>Page {query.page} of {result.pagination.totalPages}</span>{query.page < result.pagination.totalPages && <Link href={pageUrl(query.page + 1)}>Next →</Link>}</div></div></> : <section className={styles.empty}><span className={styles.emptyIcon}><Icon name="check" size={36}/></span><h2>{query.page > 1 ? "No tasks on this page." : filtered ? "No tasks match these filters." : query.mine ? "You don’t have any assigned tasks yet." : completed ? "Your completed tasks will appear here." : "A little planning goes a long way."}</h2><p>{filtered ? "Try adjusting your filters to find what you need." : "Add your first task and give every detail a place."}</p>{query.page > 1 ? <Link href={pageUrl(1)} className={styles.secondary}>Back to first page</Link> : filtered ? <Link href="/tasks" className={styles.secondary}>Clear filters</Link> : <a href="/tasks/new" className={styles.primary}>+ Add {query.mine || completed ? "task" : "your first task"}</a>}</section>}
  </main>;
}