import Image from 'next/image';
import { events, features, socialProof, tasks, wedding } from './home-data';
import { Header, PlanningButton, ThemeCards } from './home-interactions';
import { Icon } from './icon';

function SectionHeading({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) {
  return <div className="section-heading"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{children && <p className="section-intro">{children}</p>}</div>;
}
function DashboardPreview() {
  const amount = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(wedding.totalExpensePaise / 100);
  return <div className="dashboard-preview" id="workspace-preview" aria-label="Illustrative wedding dashboard">
    <div className="preview-browser"><div className="browser-dots"><i/><i/><i/></div><span>Our wedding workspace</span><span className="browser-private"><Icon name="lock" size={13}/> Private to your family</span></div>
    <div className="dashboard-body"><div className="dashboard-title"><div><p className="eyebrow">LET THE COUNTDOWN BEGIN</p><h3>{wedding.couple}’s Wedding <span className="pill">Made for us</span></h3><p><Icon name="calendar" size={14}/> {wedding.daysRemaining} days to go <span>·</span> {wedding.location}</p></div><div className="family-stack"><div className="avatars"><span>A</span><span>P</span><span>M</span></div><small>Better, together</small></div></div>
      <div className="stat-grid">{[
        ['calendar','Events','6','A celebration at every step'],['check','Tasks completed','32 / 48','The little things, taken care of'],['users','Guests invited','186','132 RSVPs received'],['rupee','Total expenses',amount,'Every expense in one place'],
      ].map(([icon,label,value,detail],i) => <div className="stat-card" key={label}><div className="stat-label">{label}<Icon name={icon} size={17}/></div><strong>{value}</strong>{i===1 ? <><div className="progress-track"><span style={{ width:'67%' }}/></div><small>{detail}</small></> : <small>{detail}</small>}</div>)}</div>
      <div className="dashboard-columns"><div><div className="panel-heading"><h4>Coming up on our calendar</h4><span>THE CELEBRATIONS</span></div><div className="dashboard-events">{events.slice(1,4).map(e => <div className="dashboard-event" key={e.name}><div className={`date-tile ${e.tone}`}><span>{e.month}</span><strong>{e.day}</strong></div><div><h5>{e.name === 'Wedding' ? 'Wedding & pheras' : e.name}</h5><p>{e.venue} · {e.time}</p></div><span className="event-count">{e.guests} guests</span></div>)}</div></div>
      <div className="task-panel"><div className="panel-heading"><h4>A little closer to the big day</h4><Icon name="check" size={17}/></div>{tasks.map(task => <div className={`preview-task ${task.done ? 'task-done' : ''}`} key={task.title}><span className="task-checkbox">{task.done && <Icon name="tick" size={12}/>}</span><div><h5>{task.title}</h5><p>{task.person} <span>· {task.due}</span></p></div><span className="task-avatar">{task.initials}</span></div>)}<span className="task-note"><Icon name="heart" size={14}/> A shared plan. A lighter to-do list.</span></div></div>
      <div className="preview-footer"><span><span className="status-dot"/> One wedding. One shared workspace.</span><span>Sample wedding preview</span></div>
    </div></div>;
}

function GuestPreview() {
  return <div className="guest-preview-grid"><article className="phone"><div className="phone-speaker"/><div className="phone-content invitation"><p className="eyebrow">YOU’RE INVITED</p><Icon name="heart" size={28}/><h3>Akshay<br/><em>& Princi</em></h3><p>With full hearts, we invite you to celebrate our wedding.</p><div className="invited-family"><small>WITH LOVE, FOR</small><strong>The Sharma family</strong><span>Up to 4 guests</span></div><div className="sample-button">Your invitation, just a tap away <Icon name="heart" size={13}/></div></div><span className="phone-caption">01 / A personal invitation</span></article>
    <article className="phone phone-raised"><div className="phone-speaker"/><div className="phone-content"><p className="eyebrow">THE CELEBRATIONS</p><h3>A place for you<br/>in every moment.</h3>{events.slice(2,4).map(e => <div className="phone-event" key={e.name}><span className="phone-event-date">{e.day} FEB</span><h4>{e.name}</h4><p>{e.time} onwards</p><p><Icon name="location" size={13}/>{e.venue}</p><small>Dress code: Festive Indian</small></div>)}<p className="phone-footnote">Only the events you’re invited to.</p></div><span className="phone-caption">02 / All the details, together</span></article>
    <article className="phone"><div className="phone-speaker"/><div className="phone-content rsvp-preview"><p className="eyebrow">WE SAVED YOU A PLACE</p><h3>Will you join<br/>the celebration?</h3><p>Your presence would mean the world to us.</p><div className="sample-choice"><Icon name="tick" size={16}/> Joyfully attending <span>●</span></div><div className="sample-choice muted-choice">Unable to attend <span>○</span></div><p className="guest-number-label">How many of you are coming?</p><div className="guest-numbers"><span>1</span><span>2</span><span className="selected-number">3</span><span>4</span></div><div className="sample-button">RSVP confirmed <Icon name="tick" size={14}/></div><p className="phone-footnote">Plans change. Your response can too.</p></div><span className="phone-caption">03 / An RSVP without the fuss</span></article></div>;
}

export function HomePage() {
  return <div className="homepage" id="top"><a className="skip-link" href="#main-content">Skip to content</a><Header/><main id="main-content">
    <section className="hero"><div className="hero-copy"><p className="hero-badge"><span/> THE MODERN WEDDING WORKSPACE</p><h1>Plan your entire wedding.<br/><em>Together.</em></h1><p className="hero-description">A shared space for all the people, plans and little details<br className="desktop-break"/> that make your Indian wedding, yours.</p><div className="hero-actions"><PlanningButton>Start Planning for Free <Icon name="arrow"/></PlanningButton><a href="#how-it-works" className="button button-secondary"><Icon name="play"/> See How It Works</a></div><div className="social-proof"><div className="avatars">{socialProof.avatars.map(a=><span key={a}>{a}</span>)}</div><strong><span className="star">★</span> {socialProof.rating}</strong><span className="social-divider"/><p>Trusted by <b>{socialProof.couples}</b> couples</p></div></div><div className="container"><DashboardPreview/></div><div className="hero-bottom-note"><Icon name="heart" size={14}/> Less coordinating. More celebrating.</div></section>
    <section className="section section-tinted" id="how-it-works"><div className="container"><SectionHeading eyebrow="SOUND FAMILIAR?" title="One wedding shouldn’t live across 40 WhatsApp chats.">The guest list is in a spreadsheet. The tasks are in a group chat.<br/>The latest plan? Someone has it. Bring it all home.</SectionHeading><div className="comparison-grid"><article className="comparison-card before-card"><span className="comparison-label">THE WAY IT USUALLY GOES</span><h3>So many details.<br/>So many different places.</h3>{['“Who has the latest guest list?”','“I thought you booked the photographer.”','“Where did we save those photos?”'].map(t=><div className="comparison-row" key={t}><span className="muted-cross">×</span>{t}</div>)}</article><article className="comparison-card after-card"><span className="comparison-label"><Icon name="sparkle" size={16}/> THE MAKE MY MARRIAGE WAY</span><h3>One shared space.<br/>A little more peace of mind.</h3>{['One guest list, with every RSVP','Clear tasks, shared with your family','Your wedding memories, all together'].map(t=><div className="comparison-row" key={t}><Icon name="tick" size={17}/>{t}</div>)}</article></div><div className="how-steps">{[['01','Create your wedding','Add your names, date and the place it all begins.'],['02','Bring your family in','Invite your favourite people to help with the planning.'],['03','Make it yours, together','Plan the events, invite the guests and enjoy the journey.']].map(([n,title,text])=><div key={n}><span>{n}</span><div><h4>{title}</h4><p>{text}</p></div></div>)}</div></div></section>
    <section className="section collaboration"><div className="container"><div className="split-heading"><div><p className="eyebrow">A FAMILY AFFAIR</p><h2>One shared plan.<br/>Many helping hands.</h2></div><p>Your wedding brings everyone together.<br/>Planning it should do the same.</p></div><div className="role-grid"><article className="role-card"><span className="icon-tile"><Icon name="heart"/></span><span className="role-label">ADMINS</span><h3>You, your partner.<br/>Your trusted circle.</h3><p>Plan every detail and invite the people who’ll help make it happen. Admins also manage members and their roles.</p><span className="role-foot">Plan together. Bring everyone in.</span></article><article className="role-card"><span className="icon-tile gold-icon"><Icon name="users"/></span><span className="role-label">MANAGERS</span><h3>Parents, cousins.<br/>Your behind-the-scenes stars.</h3><p>Manage events, tasks, guests, expenses and more. Everyone works with the same wedding information.</p><span className="role-foot">A full view of the plan. A shared sense of joy.</span></article><aside className="family-note"><div className="avatars avatars-large"><span>A</span><span>P</span><span>M</span><span>R</span></div><Icon name="heart" size={28}/><blockquote>“You bring the people.<br/>We’ll help you bring<br/>the plans together.”</blockquote><span>MADE FOR YOUR WHOLE FAMILY</span></aside></div></div></section>
    <section className="section section-tinted" id="features"><div className="container"><SectionHeading eyebrow="THE DETAILS, TAKEN CARE OF" title="Everything your wedding needs. One lovely place.">Simple tools for the big decisions and the thousand little things.</SectionHeading><div className="feature-grid">{features.map(f=><article className="feature-card" key={f.title}><span className="icon-tile"><Icon name={f.icon}/></span><span className="feature-label">{f.label}</span><h3>{f.title}</h3><p>{f.text}</p><div className="feature-sample"><span className="status-dot"/>{f.sample}</div></article>)}</div></div></section>
    <section className="section events-section"><div className="container"><div className="split-heading"><div><p className="eyebrow">MORE THAN A SINGLE DAY</p><h2>Because an Indian wedding<br/>is never just one event.</h2></div><p>A week of traditions. A lifetime of memories.<br/>Give every celebration its own moment.</p></div><div className="event-timeline">{events.map(e=><article className={`event-card event-${e.tone}`} key={e.name}><span className="timeline-dot"/><p className="event-date">{e.day} {e.month} <span>2027</span></p><h3>{e.name}</h3><p>{e.lead}</p><div><Icon name="location" size={14}/>{e.venue}</div><span className="event-time">{e.time} <span>·</span> {e.guests} guests</span></article>)}</div><p className="section-caption">YOUR TRADITIONS. YOUR TIMELINE. YOUR WAY.</p></div></section>
    <section className="section section-tinted" id="guest-experience"><div className="container"><SectionHeading eyebrow="A WARM WELCOME, WITHOUT THE WORK" title="Simple for your guests, too.">No app to download. No account to create.<br/>Just a personal invitation and a little “yes, we’ll be there.”</SectionHeading><GuestPreview/></div></section>
    <section className="section memories-section" id="memories"><div className="container memories-grid"><div className="memories-copy"><p className="eyebrow">THE MOMENTS BETWEEN THE MOMENTS</p><h2>Everyone takes photos.<br/>Now everyone can<br/>{" "}<em>share them.</em></h2><p>The happy tears. The questionable dance moves. The candid you didn’t know you needed. Bring everyone’s favourite moments into one private wedding gallery.</p><ol className="memory-steps"><li><span>1</span><div><h4>Share your gallery link or QR</h4><p>On a table, in a message, wherever your guests are.</p></div></li><li><span>2</span><div><h4>Let everyone add their favourites</h4><p>Upload from a phone. No account needed.</p></div></li><li><span>3</span><div><h4>Relive it, together</h4><p>Browse, download and treasure your wedding photos.</p></div></li></ol></div><div className="memory-visual"><div className="memory-photo photo-one">
      {/* <Image src="/images/wedding-celebration.jpg" width={700} height={420} sizes="(max-width: 760px) 90vw, 500px" alt="Family and friends celebrating an Indian wedding with flower petals"/> */}
      <div><span><span className="status-dot"/> A little love from everyone</span><Icon name="heart" size={16}/></div></div><div className="memory-photo photo-two"><Image src="/images/sangeet-memories.jpg" width={700} height={420} sizes="(max-width: 760px) 90vw, 500px" alt="Friends dancing together at a colourful Sangeet celebration"/><div><span>The dance floor memories ♡</span><span>Sangeet</span></div></div><div className="gallery-share-card"><span className="icon-tile"><Icon name="qr" size={36}/></span><div><span className="eyebrow">SCAN TO SHARE THE LOVE</span><h3>Akshay & Princi</h3><p>Your photos. Our favourite memories.</p></div></div></div></div></section>
    <section className="section section-tinted" id="themes"><div className="container"><SectionHeading eyebrow="A LITTLE CORNER OF THE INTERNET, ALL YOURS" title="Your wedding gets a home of its own.">Your names. Your story. Your celebrations.<br/>Choose a theme and make your guests feel welcome before they arrive.</SectionHeading><ThemeCards/><p className="theme-note"><Icon name="play" size={16}/> Loved ones joining from afar? Add your YouTube livestream.</p></div></section>
    <section className="section trust-section"><div className="container"><SectionHeading eyebrow="THOUGHTFULLY BUILT, FROM THE START" title="For your family. For your peace of mind."/><div className="trust-grid">{[['lock','Private wedding workspace','Your planning details stay with your wedding members.'],['users','Together, with clear roles','Admins manage members. Everyone helps with the plans.'],['heart','No guest accounts','Invitations and galleries open with secure share links.'],['photo','Memories to keep','View and download the photos that mean the most.']].map(([icon,title,description])=><div key={title}><Icon name={icon} size={25}/><h3>{title}</h3><p>{description}</p></div>)}</div></div></section>
    <section className="final-section"><div className="container"><div className="final-cta"><Icon name="heart" size={30}/><p className="eyebrow">HERE’S TO THE BEGINNING OF EVERYTHING</p><h2>Your wedding already has<br/>enough moving parts.</h2><p>Bring them together in one beautifully organised place.<br/>And make a little more room for the joy.</p><PlanningButton className="button button-gold">Start Planning for Free <Icon name="arrow"/></PlanningButton><div className="cta-notes"><span><Icon name="tick" size={14}/> Made for Indian weddings</span><span><Icon name="tick" size={14}/> Better with your family</span></div></div></div></section>
    </main><footer className="site-footer"><div className="container"><div className="footer-top"><div className="footer-brand"><a href="#top"><Image src="/images/make-my-marriage-logo.svg" width={240} height={60} alt="Make My Marriage"/></a><p>One wedding. A thousand little details.<br/>One place to bring them all together.</p><span>MADE WITH LOVE, FOR YOUR BIG DAY.</span></div><div><h4>EXPLORE</h4><a href="#features">Our features</a><a href="#how-it-works">How it works</a><a href="#themes">Wedding themes</a></div><div><h4>CELEBRATE</h4><a href="#guest-experience">Guest invitations</a><a href="#memories">Photo sharing</a><a href="#workspace-preview">Your workspace</a></div><div className="footer-note"><Icon name="heart" size={23}/><p>Less coordinating.<br/><em>More celebrating.</em></p><a href="#top">Back to the beginning ↑</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Make My Marriage</span><span>Made for the moments that matter.</span></div></div></footer></div>;
}