"use client";
/* eslint-disable @next/next/no-img-element -- Signed private photos must not enter the public image optimiser cache. */
import { useCallback, useEffect, useRef, useState } from "react";
import { Icon } from "@/components/home/icon";
import { useWeddingDraftSession } from "@/components/wedding/draft-session";
import type { PhotoPage, PhotoView } from "@/modules/photos/schemas";
import { UploadQueue, galleryRequest, type GalleryEvent } from "./upload-queue";
import styles from "./gallery.module.css";
const date = (value: string) => new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value));
export function Gallery({ events }: { events: GalleryEvent[] }) {
  const [photos, setPhotos] = useState<PhotoView[]>([]); const [total, setTotal] = useState(0); const [cursor, setCursor] = useState<string | null>(null);
  const [filter, setFilter] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [selected, setSelected] = useState<string | null>(null); const [actionError, setActionError] = useState(""); const [busy, setBusy] = useState(false); const [imageFailed, setImageFailed] = useState(false);
  const upload = useRef<HTMLDialogElement>(null); const viewer = useRef<HTMLDialogElement>(null); const deletion = useRef<HTMLDialogElement>(null);
  const controller = useRef<AbortController | null>(null); const version = useRef(0); const retryCursor = useRef<string | undefined>(undefined); const mounted = useRef(true); const touch = useRef<number | null>(null);
  const session = useWeddingDraftSession(); const expire = session.expire;
  const load = useCallback(async (after?: string) => {
    controller.current?.abort(); const abort = new AbortController(); controller.current = abort; const requestVersion = ++version.current;
    retryCursor.current = after; setLoading(true); setError("");
    try {
      const query = new URLSearchParams({ limit: "24", ...(filter ? { eventId: filter } : {}), ...(after ? { cursor: after } : {}) });
      const response = await fetch(`/api/photos?${query}`, { cache: "no-store", signal: abort.signal }); const result = await response.json();
      if (requestVersion !== version.current || !mounted.current) return;
      if (response.status === 401) expire();
      if (!response.ok) throw new Error(result.error?.message ?? "We couldn’t load your photos.");
      const page = result as PhotoPage; setPhotos(old => after ? [...old, ...page.data.filter(photo => !old.some(item => item.id === photo.id))] : page.data); setTotal(page.total); setCursor(page.pagination.nextCursor);
    } catch (error) { if (!abort.signal.aborted && mounted.current) setError(error instanceof Error ? error.message : "We couldn’t load your photos. Please retry."); }
    finally { if (requestVersion === version.current && mounted.current) setLoading(false); }
  }, [filter, expire]);
  useEffect(() => { mounted.current = true; let cancelled = false; queueMicrotask(() => { if (!cancelled) void load(); }); return () => { cancelled = true; mounted.current = false; controller.current?.abort(); }; }, [load]);
  const index = photos.findIndex(photo => photo.id === selected); const photo = photos[index];
  function eventName(id: string | null) { return events.find(event => event.id === id)?.name ?? "Wedding Memories"; }
  function open(photo: PhotoView) { setSelected(photo.id); setActionError(""); setImageFailed(false); viewer.current?.showModal(); }
  function navigate(delta: number) { const next = photos[index + delta]; if (next) { setSelected(next.id); setActionError(""); setImageFailed(false); } }
  function refresh() { viewer.current?.close(); setSelected(null); void load(); }
  async function download() { if (!photo || busy) return; setBusy(true); setActionError(""); try { if (!await session.revalidate()) throw new Error("Please sign in again before downloading."); const result = await galleryRequest(`/api/photos/${photo.id}/download`); const anchor = document.createElement("a"); anchor.href = result.data.url; anchor.download = photo.originalFilename; anchor.rel = "noreferrer"; document.body.append(anchor); anchor.click(); anchor.remove(); } catch (error) { setActionError(error instanceof Error ? error.message : "Download failed. Please retry."); } finally { setBusy(false); } }
  async function remove() { if (!photo || busy) return; setBusy(true); setActionError(""); try { if (!await session.revalidate()) throw new Error("Please sign in again before deleting."); await galleryRequest(`/api/photos/${photo.id}`, { method: "DELETE" }); deletion.current?.close(); viewer.current?.close(); setSelected(null); setNotice("Photo deleted."); await load(); } catch (error) { setActionError(error instanceof Error ? error.message : "We couldn’t delete this photo. Please retry."); } finally { setBusy(false); } }
  return <main id="wedding-content" className={styles.gallery}>
    <header className={styles.heading}><div><p className={styles.eyebrow}>Your celebration, remembered</p><h1>Wedding Gallery</h1><p className={styles.muted}>All your wedding memories, beautifully gathered in one place. <br/>Upload, relive, and keep every little moment close.</p></div><div className={styles.actions}><span className={styles.count}><Icon name="photo" size={17}/>{loading && !photos.length ? "Your photos" : `${total} ${filter ? "matching " : ""}photos`}</span><button className={styles.primary} onClick={() => upload.current?.showModal()}>＋ Upload photos</button></div></header>
    <section className={styles.toolbar} aria-label="Gallery filters"><div className={styles.filters}>{[{ id: "", name: "All photos" }, ...events, { id: "other", name: "Wedding Memories" }].map(event => <button key={event.id} aria-pressed={filter === event.id} onClick={() => { if (filter !== event.id) { setPhotos([]); setCursor(null); setSelected(null); setFilter(event.id); } }}>{event.name}{"archived" in event && event.archived ? " (archived)" : ""}</button>)}</div><button className={styles.textButton} disabled={loading} onClick={refresh}>Refresh</button></section>
    {notice && <p role="status" className={styles.notice}>{notice}</p>}
    {error && <div className={styles.errorPanel} role="alert"><strong>We couldn’t load your gallery</strong><p>{error}</p><button className={styles.secondary} onClick={() => void load(retryCursor.current)}>Try again</button></div>}
    {!loading && !error && !photos.length && <section className={styles.empty}><div className={styles.emptyIcon}><Icon name="photo" size={44}/></div><p className={styles.eyebrow}>Every photo tells your story</p><h2>{filter ? "No photos here yet" : "Your memories begin here"}</h2><p className={styles.muted}>{filter ? "Upload photos for this event, or explore the rest of your gallery." : "From the first celebration to the last dance, give your favourite moments a home."}</p><button className={styles.primary} onClick={() => upload.current?.showModal()}>＋ Upload your first photos</button>{filter && <button className={styles.textButton} onClick={() => setFilter("")}>View all photos</button>}</section>}
    <div className={styles.grid} aria-busy={loading}>{photos.map((photo, index) => <button className={styles.card} key={photo.id} onClick={() => open(photo)} aria-label={`View ${photo.originalFilename}`}><div className={`${styles.photoWrap} ${index % 5 === 0 ? styles.portrait : ""}`}><img src={photo.url} alt={photo.originalFilename} loading="lazy" decoding="async"/><span className={styles.eventBadge}>{eventName(photo.eventId)}</span><span className={styles.viewHint}>View photo ↗</span></div><div className={styles.cardCaption}><strong title={photo.originalFilename}>{photo.originalFilename}</strong><div><span>{(photo.sizeBytes / 1024 / 1024).toFixed(1)} MB</span><time dateTime={photo.createdAt}>{date(photo.createdAt)}</time></div></div></button>)}</div>
    {loading && <div className={styles.loading} role="status"><span/>Gathering your memories…</div>}
    {!!photos.length && <footer className={styles.pagination}><p>Showing {photos.length} of {total} photos</p>{cursor && <button className={styles.secondary} disabled={loading} onClick={() => void load(cursor)}>Load more photos ↓</button>}<span className={styles.muted}>A little collection of your forever.</span></footer>}
    <UploadQueue dialog={upload} events={events} onUploaded={() => { setNotice("Your uploaded photos are saved."); void load(); }}/>
    <dialog ref={viewer} className={styles.viewer} aria-label="Photo viewer" onKeyDown={event => { if (deletion.current?.open || busy) return; if (event.key === "ArrowRight") navigate(1); if (event.key === "ArrowLeft") navigate(-1); }} onClose={() => setSelected(null)}>{photo && <><header className={styles.viewerHead}><span>Photo {index + 1} of {photos.length}{cursor ? " loaded" : ""} <b>· {eventName(photo.eventId)}</b></span><button aria-label="Close photo viewer" onClick={() => viewer.current?.close()}><Icon name="close"/></button></header><div className={styles.viewerImage} onTouchStart={event => { touch.current = event.touches[0].clientX; }} onTouchEnd={event => { if (touch.current !== null && !busy) { const delta = event.changedTouches[0].clientX - touch.current; if (Math.abs(delta) > 60) navigate(delta < 0 ? 1 : -1); } touch.current = null; }}><button aria-label="Previous photo" disabled={index === 0 || busy} onClick={() => navigate(-1)}>‹</button>{imageFailed ? <div><p>This photo couldn’t load. Its private link may have expired.</p><button className={styles.secondary} onClick={refresh}>Refresh gallery</button></div> : <img key={photo.id + photo.url} src={photo.url} alt={photo.originalFilename} onError={() => setImageFailed(true)}/>}<button aria-label="Next photo" disabled={index === photos.length - 1 || busy} onClick={() => navigate(1)}>›</button></div><footer className={styles.viewerFoot}><div><h2>{photo.originalFilename}</h2><p>{eventName(photo.eventId)} · Uploaded {date(photo.createdAt)} · {(photo.sizeBytes / 1024 / 1024).toFixed(1)} MB</p></div><div className={styles.actions}><button className={styles.secondary} disabled={busy} onClick={() => void download()}>↓ Download</button><button className={styles.deleteButton} disabled={busy} onClick={() => { setActionError(""); deletion.current?.showModal(); }}>Delete photo</button></div></footer>{actionError && <p role="alert" className={styles.viewerError}>{actionError}</p>}</>}</dialog>
    <dialog ref={deletion} className={styles.confirmDialog} aria-labelledby="delete-title" onCancel={event => { if (busy) event.preventDefault(); }}><h2 id="delete-title">Delete this photo?</h2>{photo && <img className={styles.deleteThumb} src={photo.url} alt={photo.originalFilename}/>}<p>This will permanently remove the photo from your wedding gallery. This action can’t be undone.</p>{actionError && <p role="alert" className={styles.error}>{actionError}</p>}<div className={styles.actions}><button className={styles.secondary} autoFocus disabled={busy} onClick={() => { deletion.current?.close(); setActionError(""); }}>Keep photo</button><button className={styles.danger} disabled={busy} onClick={() => void remove()}>{busy ? "Deleting…" : "Delete photo"}</button></div></dialog>
  </main>;
}